// Generated by CoffeeScript 1.3.3
(function() {
  var $, $window, navEl, root;

  root = this;

  $ = root.jQuery || root.$;

  $window = $(window);

  navEl = $('.nav').each(function() {
    var anchors, currentEl, el, update;
    el = $(this);
    anchors = [];
    currentEl = null;
    el.find('a').each(function() {
      var anchor, link, top;
      link = $(this);
      anchor = link.attr('href');
      top = $(anchor).offset().top;
      return anchors.push({
        top: top,
        anchor: anchor,
        el: link
      });
    });
    anchors.sort(function(a, b) {
      return a.top - b.top;
    });
    update = function(event) {
      var height, i, top;
      top = $window.scrollTop();
      height = $window.height();
      i = 0;
      while (i < anchors.length && anchors[i].top < (top - height / 3) && anchors[i].top + anchors[i].el.outerHeight() < top) {
        console.log(i, anchors[i].top, anchors[i].top + anchors[i].el.outerHeight(), top);
        ++i;
      }
      console.log(i, anchors[i].top, anchors[i].top + anchors[i].el.outerHeight(), top);
      i = Math.min(anchors.length - 1, i);
      if (currentEl !== anchors[i].el) {
        if (currentEl) {
          currentEl.removeClass('highlight');
        }
        return currentEl = anchors[i].el.addClass('highlight');
      }
    };
    $window.on('resize scroll', update);
    return update();
  });

}).call(this);
