// Generated by CoffeeScript 1.3.3
(function() {
  var $, navEl, navList, root;

  root = this;

  $ = root.jQuery || root.$;

  navEl = $('.nav').each(function() {
    var el, listEl, openHeight, showing, toggleButton;
    el = $(this);
    listEl = el.find('ul');
    toggleButton = el.find('.toggle-button');
    openHeight = listEl.height();
    console.log(openHeight);
    showing = false;
    listEl.addClass('collapsed');
    return toggleButton.on('click', function(event) {
      var from, to;
      listEl.stop();
      to = showing ? 0 : openHeight;
      from = listEl.height();
      showing = !showing;
      return listEl.height(from).animate({
        height: to + 'px'
      }, 300, function() {
        return listEl.toggleClass('collapsed', !showing).css({
          height: ''
        });
      });
    });
  });

  navList = navEl.find('ul');

}).call(this);
