// Generated by CoffeeScript 1.3.3
(function() {
  var $, $window, navEl, root;

  root = this;

  $ = root.jQuery || root.$;

  $window = $(window);

  navEl = $('.nav').each(function() {
    var anchors, calculate, currentEl, el, update;
    el = $(this);
    anchors = [];
    currentEl = null;
    update = function(event) {
      var height, i, top;
      top = $window.scrollTop();
      height = $window.height();
      i = 0;
      while (i < anchors.length && anchors[i].top < top) {
        ++i;
      }
      i = Math.min(anchors.length - 1, i);
      if (currentEl !== anchors[i].el) {
        if (currentEl) {
          currentEl.removeClass('highlight');
        }
        return currentEl = anchors[i].el.addClass('highlight');
      }
    };
    calculate = function() {
      var topOff;
      topOff = el.css('bottom') === 'auto' ? el.height() : 0;
      anchors = [];
      el.find('a').each(function() {
        var anchor, anchorEl, link, top;
        link = $(this);
        anchor = link.attr('href');
        anchorEl = $(anchor);
        top = anchorEl.offset().top + topOff;
        anchors.push({
          top: top,
          anchor: anchor,
          el: link,
          anchorEl: anchorEl
        });
        return link.data('anchorEl', anchorEl);
      }).off('click').on('click', function(event) {
        var dummy;
        $('body').animate({
          scrollTop: $(this).data('anchorEl').offset().top - topOff
        }, 200);
        dummy = $('<div></div>', {
          id: $(this).attr('href').replace(/^#/, ''),
          css: {
            position: 'absolute',
            visibility: 'hidden',
            top: $window.scrollTop() + 'px'
          }
        }).prependTo('body');
        return setTimeout(function() {
          return dummy.remove();
        }, 20);
      });
      anchors.sort(function(a, b) {
        return a.top - b.top;
      });
      return update();
    };
    calculate();
    $window.on('scroll', update);
    return $window.on('resize', calculate);
  });

}).call(this);
